float notaProva = 8.5F;
int quantidadeAlunos = 42;
string nomeCurso = "Fundamentos de C#";
bool pagamentoEfetuado = false;
char digitoVerificador = '7';
Console.WriteLine(notaProva);
Console.WriteLine(quantidadeAlunos);
Console.WriteLine(nomeCurso);
Console.WriteLine(pagamentoEfetuado);
Console.WriteLine(digitoVerificador);